export const siteConfig = {
  name: "Zain Javed - Full Stack Developer",
  authorName: "Zain Javed",
  username: "zaykhere",
  description:
    "Zain Javed - A Full Stack Web Developer with 4+ years of experience designing reliable backends, modern frontends, and production-ready systems.",
  url: "https://zainthedev.com",
  links: {
    twitter: "https://x.com",
    github: "https://github.com/zaykhere",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },
  ogImage:
    "https://res.cloudinary.com/zainhither/image/upload/v1773685112/portfolio/Untitled_gg0fxx.png",
  iconIco:
    "https://res.cloudinary.com/zainhither/image/upload/v1773685189/portfolio/favicon_fdmy6f.ico",
  logoIcon:
    "https://res.cloudinary.com/zainhither/image/upload/v1773685154/portfolio/Gemini_Generated_Image_pmvt6jpmvt6jpmvt-removebg-preview_wfaw70.png",
  keywords: [
    "Zain Javed",
    "Node.js Developer",
    "React Native Developer",
    "JavaScript Developer",
    "Postgres",
    "Apache Kafka",
    "MySQL",
    "AI Engineer",
    "Software Engineer",
    "Full Stack Developer",
    "Machine Learning",
    "Data Engineering",
    "UBS",
    "Python Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "Databricks",
    "AI Startups",
    "Software Development",
    "Web Developer",
    "Backend Developer",
    "Frontend Developer",
    "Tech Portfolio",
  ],
};
